[package]
name = "bzl-exec-log-parser"
version = "0.1.0"
edition = "2024"

[dependencies]

# Protobuf dependencies
prost = "0.12"
prost-types = "0.12"

# CLI argument parsing
clap = { version = "4.0", features = ["derive"] }

# JSON serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
prost-build = "0.12"
