[package]
name = "bzl-exec-log-parser"
version = "0.1.0"
edition = "2024"

[dependencies]

# Protobuf dependencies
prost = "0.13"
prost-types = "0.13"

# CLI argument parsing
clap = { version = "4.5", features = ["derive"] }

# Error handling
anyhow = "1.0"

[build-dependencies]
prost-build = "0.13"
